package CheckApp;


/**
* CheckApp/servicioHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from time.idl
* sábado 23 de mayo de 2020 09:49:26 PM CDT
*/

abstract public class servicioHelper
{
  private static String  _id = "IDL:CheckApp/servicio:1.0";

  public static void insert (org.omg.CORBA.Any a, CheckApp.servicio that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CheckApp.servicio extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CheckApp.servicioHelper.id (), "servicio");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CheckApp.servicio read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_servicioStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CheckApp.servicio value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CheckApp.servicio narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CheckApp.servicio)
      return (CheckApp.servicio)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CheckApp._servicioStub stub = new CheckApp._servicioStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CheckApp.servicio unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CheckApp.servicio)
      return (CheckApp.servicio)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CheckApp._servicioStub stub = new CheckApp._servicioStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
