package CheckApp;


/**
* CheckApp/servicio.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from time.idl
* sábado 23 de mayo de 2020 09:49:26 PM CDT
*/

public interface servicio extends servicioOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface servicio
