package CheckApp;


/**
* CheckApp/servicioOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from time.idl
* sábado 23 de mayo de 2020 09:49:26 PM CDT
*/

public interface servicioOperations 
{
  int get_id (int id);
  String get_pass (String pass);
  String get_name (String name);
  String get_date ();
  int get_time ();
  void shutdown ();
} // interface servicioOperations
